# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d602f023815b63958eaadff47090dcc95752f99c39469cd93a77deae45915788b2e4500f4dc36eecc7f58b3546625b819f6366a9de63240b2dc3a2259c801e3b

test:
  secret_key_base: 81d522ae2d664b527da5a4c66ca6b2ada1c2fe2319f75b35816fd7b6ecf69b4d341035d1561d463e04f20483deabad01c4f78d4a0718756f7e8cd37bcf002fd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
